autodidact/app/urls.py
from django.conf.urls import url
from django.contrib.auth.views import logout

from app import views

app_name = 'app'

urlpatterns = [
    url(r'^$', views.main, name='main'),
    url(r'^login$', views.login_user, name='login'),
    url(r'^profile$', views.user_profile, name='userProfile'),

    url(r'^posts$', views.get_posts, name='posts'),
    url(r'^tags$', views.get_tags, name='tags'),
    url(r'^users$', views.get_users, name='users'),
    url(r'^user/profile/$', views.get_profile, name='userProfile'),

    url(r'^post/details/(?P<pk>[0-9]+)$', views.post_details, name='postDetails'),
    url(r'^tag/details/(?P<pk>[0-9]+)$', views.tag_details, name='tagDetails'),
    url(r'^user/details/(?P<pk>[0-9]+)$', views.user_details, name='userDetails'),

    url(r'^add/tag$', views.add_tag, name='addTag'),
    url(r'^add/post$', views.add_post, name='addPost'),
    url(r'^add/answer$', views.add_answer, name='addAnswer'),
    url(r'^add/comment$', views.add_comment, name='addComment'),

    url(r'^update/tag$', views.update_tag, name='updateTag'),
    url(r'^update/answer/accept$', views.update_answer_accept, name='updateAnswerAccept'),

    url(r'^search/tags$', views.search_tags, name='searchTags'),

    url(r'^vote$', views.vote, name='vote'),

    url(r'^logout$', logout, {'next_page': '/'}, name='logout'),
]

autodidact/autodidact/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('app.urls', namespace='app'))
]

autodidact/app/models.py
from django.contrib.auth.models import User
from django.db import models


class ForumUser(models.Model):
    django_user = models.OneToOneField(User)
    reputation = models.IntegerField(default=0)

    def __str__(self):
        return str(self.django_user.username)


class Tag(models.Model):
    name = models.CharField(max_length=50, unique=True)
    use_count = models.IntegerField(default=0)
    creation_time = models.DateTimeField(auto_now_add=True)
    created_by = models.ForeignKey('ForumUser')

    def __str__(self):
        return str(self.name) + ' ;' + str(self.created_by)


class Post(models.Model):
    title = models.CharField(max_length=100)
    description = models.CharField(max_length=1000)
    tags = models.ManyToManyField(Tag)
    accepted_answer = models.OneToOneField('Answer', null=True, related_name='accepted_answer')
    up_voters = models.ManyToManyField('ForumUser', related_name='up_voted_post')
    down_voters = models.ManyToManyField('ForumUser', related_name='down_voted_post')
    viewers = models.ManyToManyField('ForumUser', related_name='viewed_post')
    closed = models.BooleanField(default=False)
    creation_time = models.DateTimeField(auto_now_add=True)
    created_by = models.ForeignKey('ForumUser', related_name='created_post')

    def __str__(self):
        return str(self.title) + ' ;' + str(self.creation_time)


class Answer(models.Model):
    description = models.CharField(max_length=1000)
    post = models.ForeignKey('Post')
    up_voters = models.ManyToManyField('ForumUser', related_name='up_voted_answer')
    down_voters = models.ManyToManyField('ForumUser', related_name='down_voted_answer')
    creation_time = models.DateTimeField(auto_now_add=True)
    created_by = models.ForeignKey('ForumUser', related_name='created_answer')

    def __str__(self):
        return str(self.description)[:20] + ' ;' + str(self.creation_time)


class Comment(models.Model):
    description = models.CharField(max_length=100)
    post = models.ForeignKey('Post', null=True)
    answer = models.ForeignKey('Answer', null=True)
    creation_time = models.DateTimeField(auto_now_add=True)
    created_by = models.ForeignKey('ForumUser', related_name='created_comment')

    def __str__(self):
        return str(self.description)[:20] + ' ;' + str(self.creation_time)

autodidact/app/templates/add_comment.html
<form method="post" action="{% url 'app:addComment' %}"
      style="margin-bottom: 0;">
    {% csrf_token %}
    <div class="btn-group inline" style="width: 100%; height: 48px;">
        <input name="description" class="form-control" style="border: 0;"
               placeholder="Add a comment">
        <input type="hidden" name="post_id" value="{{ post.id }}">
        <input type="hidden" name="answer_id" value="{{ answer.id }}">
        <button type="submit" style="background-color: #006dd9; width: 250px; color: white" class="btn">Add comment
        </button>
    </div>
</form>

autodidact/app/templates/base.html
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">

    {% load staticfiles %}
    <link rel="shortcut icon" type="image/x-icon" href="{% static 'app/img/logo_autodidact.ico' %}"/>
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.0.13/css/all.css"
          integrity="sha384-DNOHZ68U8hZfKXOrtjWvjxusGo9WQnrNx2sqG0tfsghAvtVlRW3tvkXWZh58N9jp"
          crossorigin="anonymous">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css"
          integrity="sha384-WskhaSGFgHYWDcbwN70/dfYBj47jz9qbsMId/iRN3ewGhXQFZCSftd1LZCfmhktB"
          crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'app/css/style.css' %}">
    <title>Autodidact</title>

    {% block head_content %}
    {% endblock %}

</head>

<body>
<nav class="navbar navbar-expand-sm navbar-dark bg-dark p-0">
    <div class="container">
        <a href="{% url 'app:main' %}" class="navbar-brand">
            <img src="{% static 'app/img/iiits_logo.png' %}"
                 style="width: 32px; height: 32px; margin-right: 8px;">
            Autodidact
        </a>
        <button class="navbar-toggler" data-toggle="collapse" data-target="#navbarCollapse">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav">
                <li class="nav-item px-2">
                    <a href="{% url 'app:main' %}" class="nav-link active">Forum</a>
                </li>
                <li class="nav-item px-2">
                    <a href="{% url 'app:posts' %}" class="nav-link">Posts</a>
                    {#TODO#}
                </li>
                <li class="nav-item px-2">
                    <a href="{% url 'app:tags' %}" class="nav-link">Tags</a>
                    {#TODO#}
                </li>
                <li class="nav-item px-2">
                    <a href="{% url 'app:users' %}" class="nav-link">Users</a>
                    {#TODO#}
                </li>
            </ul>

            <ul class="navbar-nav ml-auto">

                {% if user.is_authenticated %}
                    <li class="nav-item dropdown mr-3">
                        <a href="#" class="nav-link dropdown-toggle" data-toggle="dropdown">
                            <i class="fas fa-user"></i> {{ user.username }}
                        </a>
                        <div class="dropdown-menu">
                            <a href="{% url 'app:userProfile' %}" class="dropdown-item">
                               <i class="fas fa-user-circle"></i> View Profile
                            </a>
{#                            <a href="settings.html" class="dropdown-item">#}
{#                                <i class="fas fa-cog"></i> Settings#}
{#                            </a>#}
                        </div>
                    </li>
                    <li class="nav-item">
                        <a href="{% url 'app:logout' %}" class="nav-link">
                            <i class="fas fa-sign-out-alt"></i> Logout
                        </a>
                    </li>
                {% else %}
                    <li class="nav-item">
                        <a href="{% url 'app:login' %}" class="nav-link">
                            <i class="fas fa-user-alt"></i> Login
                        </a>
                    </li>
                {% endif %}
            </ul>
        </div>
    </div>
</nav>

{% block body_content %}
{% endblock %}

<footer id="main-footer" class="bg-dark text-white p-5 mt-5">
    <div class="container">
        <div class="row">
            <div class="col">
                <p class="lead text-center">
                    Copyright &copy;
                    <span id="year"></span>
                    <br>ASE Project Team A-7
                </p>
            </div>
        </div>
    </div>
</footer>

{% block below_footer_content %}
{% endblock %}

<script src="http://code.jquery.com/jquery-3.3.1.min.js" integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8="
        crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js"
        integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49"
        crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.1/js/bootstrap.min.js"
        integrity="sha384-smHYKdLADwkXOn1EmN1qk/HfnUcbVRZyYmZ4qpPea6sjB/pTJ0euyQp0Mk8ck+5T"
        crossorigin="anonymous"></script>
<script> $('#year').text(new Date().getFullYear()); </script>

{% block below_body_content %}
{% endblock %}

</body>

</html>

autodidact/app/templates/comment.html
<form method="post" action="#" style="margin-bottom: 0">
    {% csrf_token %}
    <div class="btn-group inline" style="width: 100%; height: 48px;">
        <input disabled class="form-control" style="border: 0; color: black" value="{{ comment.description }}">
        <button type="submit" style="background-color: #d7d7d7; width: 250px;"
                class="btn">{{ comment.created_by }}</button>
    </div>
</form>

autodidact/app/templates/details.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.0.13/css/all.css"
          integrity="sha384-DNOHZ68U8hZfKXOrtjWvjxusGo9WQnrNx2sqG0tfsghAvtVlRW3tvkXWZh58N9jp"
          crossorigin="anonymous">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css"
          integrity="sha384-WskhaSGFgHYWDcbwN70/dfYBj47jz9qbsMId/iRN3ewGhXQFZCSftd1LZCfmhktB"
          crossorigin="anonymous">
    <link rel="stylesheet" href="css/style.css">
    <title>Bootstrap Theme</title>
</head>

<body>
<nav class="navbar navbar-expand-sm navbar-dark bg-dark p-0">
    <div class="container">
        <a href="{% url 'app:main' %}" class="navbar-brand">Autodidact</a>
        <button class="navbar-toggler" data-toggle="collapse" data-target="#navbarCollapse">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav">
                <li class="nav-item px-2">
                    <a href="{% url 'app:main' %}" class="nav-link active">Forum</a>
                </li>
                <li class="nav-item px-2">
                    <a href="{% url 'app:posts' %}" class="nav-link">Posts</a>
                    {#TODO#}
                </li>
                <li class="nav-item px-2">
                    <a href="{% url 'app:tags' %}" class="nav-link">Tags</a>
                    {#TODO#}
                </li>
                <li class="nav-item px-2">
                    <a href="{% url 'app:users' %}" class="nav-link">Users</a>
                    {#TODO#}
                </li>
            </ul>

            <ul class="navbar-nav ml-auto">
                <li class="nav-item dropdown mr-3">
                    <a href="#" class="nav-link dropdown-toggle" data-toggle="dropdown">
                        <i class="fas fa-user"></i> {{ user.username }}
                    </a>
                    <div class="dropdown-menu">
                        <a href="profile.html" class="dropdown-item">
                            <i class="fas fa-user-circle"></i> Profile
                        </a>
                        <a href="{% url 'app:userDetails' user.id%}" class="dropdown-item">
                            <i class="fas fa-cog"></i> Settings
                        </a>
                    </div>
                </li>
                <li class="nav-item">
                    <a href="{% url 'app:login' %}" class="nav-link">
                        <i class="fas fa-user-alt"></i> Login
                    </a>
                </li>

            </ul>
        </div>
    </div>
</nav>

<!-- HEADER -->
<header id="main-header" class="py-2 bg-primary text-white">
    <div class="container">
        <div class="row">
            <div class="col-md-6">
                <h1>
                    Post One</h1>
            </div>
        </div>
    </div>
</header>

<!-- ACTIONS -->
<section id="actions" class="py-4 mb-4 bg-light">
    <div class="container">
        <div class="row">
            <div class="col-md-3">
                <a href="index.html" class="btn btn-light btn-block">
                    <i class="fas fa-arrow-left"></i> Back To Dashboard
                </a>
            </div>
            <div class="col-md-3">
                <a href="index.html" class="btn btn-success btn-block">
                    <i class="fas fa-check"></i> Save Changes
                </a>
            </div>
            <div class="col-md-3">
                <a href="index.html" class="btn btn-danger btn-block">
                    <i class="fas fa-trash"></i> Delete Post
                </a>
            </div>
        </div>
    </div>
</section>

<!-- DETAILS -->
<section id="details">
    <div class="container">
        <div class="row">
            <div class="col">
                <div class="card">
                    <div class="card-header">
                        <h4>Edit Post</h4>
                    </div>
                    <div class="card-body">
                        <form>
                            <div class="form-group">
                                <label for="title">Title</label>
                                <input type="text" class="form-control" value="Post One">
                            </div>
                            <div class="form-group">
                                <label for="category">Category</label>
                                <select class="form-control">
                                    <option value="" selected>Web Development</option>
                                    <option value="">Tech Gadgets</option>
                                    <option value="">Business</option>
                                    <option value="">Health & Wellness</option>
                                </select>
                            </div>
                            <div class="form-group">
                                <label for="image">Upload Image</label>
                                <div class="custom-file">
                                    <input type="file" class="custom-file-input" id="image">
                                    <label for="image" class="custom-file-label">Choose File</label>
                                </div>
                                <small class="form-text text-muted">Max Size 3mb</small>
                            </div>
                            <div class="form-group">
                                <label for="body">Body</label>
                                <textarea name="editor1" class="form-control">Lorem ipsum dolor sit amet consectetur adipisicing elit. Repellat culpa nam cumque voluptatum. Possimus recusandae porro architecto officiis illo dignissimos ratione aut officia reprehenderit! Iure cum numquam fugit doloremque quis ullam illo odit, odio voluptates non quisquam laboriosam consectetur quasi perspiciatis! Sapiente minus aperiam nobis molestias autem ut praesentium laudantium?</textarea>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>

<!-- FOOTER -->
<footer id="main-footer" class="bg-dark text-white mt-5 p-5">
    <div class="container">
        <div class="row">
            <div class="col">
                <p class="lead text-center">
                    Copyright &copy;
                    <span id="year"></span>
                    Blogen
                </p>
            </div>
        </div>
    </div>
</footer>


<!-- MODALS -->

<!-- ADD POST MODAL -->
<div class="modal fade" id="addPostModal">
    <div class="modal-dialog modal-lg">
        <div class="modal-content">
            <div class="modal-header bg-primary text-white">
                <h5 class="modal-title">Add Post</h5>
                <button class="close" data-dismiss="modal">
                    <span>&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <form>
                    <div class="form-group">
                        <label for="title">Title</label>
                        <input type="text" class="form-control">
                    </div>
                    <div class="form-group">
                        <label for="category">Category</label>
                        <select class="form-control">
                            <option value="">Web Development</option>
                            <option value="">Tech Gadgets</option>
                            <option value="">Business</option>
                            <option value="">Health & Wellness</option>
                        </select>
                    </div>
                    <div class="form-group">
                        <label for="image">Upload Image</label>
                        <div class="custom-file">
                            <input type="file" class="custom-file-input" id="image">
                            <label for="image" class="custom-file-label">Choose File</label>
                        </div>
                        <small class="form-text text-muted">Max Size 3mb</small>
                    </div>
                    <div class="form-group">
                        <label for="body">Body</label>
                        <textarea name="editor1" class="form-control"></textarea>
                    </div>
                </form>
            </div>
            <div class="modal-footer">
                <button class="btn btn-primary" data-dismiss="modal">Save Changes</button>
            </div>
        </div>
    </div>
</div>

<!-- ADD CATEGORY MODAL -->
<div class="modal fade" id="addCategoryModal">
    <div class="modal-dialog modal-lg">
        <div class="modal-content">
            <div class="modal-header bg-success text-white">
                <h5 class="modal-title">Add Category</h5>
                <button class="close" data-dismiss="modal">
                    <span>&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <form>
                    <div class="form-group">
                        <label for="title">Title</label>
                        <input type="text" class="form-control">
                    </div>
                </form>
            </div>
            <div class="modal-footer">
                <button class="btn btn-success" data-dismiss="modal">Save Changes</button>
            </div>
        </div>
    </div>
</div>

<!-- ADD USER MODAL -->
<div class="modal fade" id="addUserModal">
    <div class="modal-dialog modal-lg">
        <div class="modal-content">
            <div class="modal-header bg-warning text-white">
                <h5 class="modal-title">Add User</h5>
                <button class="close" data-dismiss="modal">
                    <span>&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <form>
                    <div class="form-group">
                        <label for="name">Name</label>
                        <input type="text" class="form-control">
                    </div>
                    <div class="form-group">
                        <label for="email">Email</label>
                        <input type="email" class="form-control">
                    </div>
                    <div class="form-group">
                        <label for="password">Password</label>
                        <input type="password" class="form-control">
                    </div>
                    <div class="form-group">
                        <label for="password2">Confirm Password</label>
                        <input type="password" class="form-control">
                    </div>
                </form>
            </div>
            <div class="modal-footer">
                <button class="btn btn-warning" data-dismiss="modal">Save Changes</button>
            </div>
        </div>
    </div>
</div>


<script src="http://code.jquery.com/jquery-3.3.1.min.js" integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8="
        crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js"
        integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49"
        crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.1/js/bootstrap.min.js"
        integrity="sha384-smHYKdLADwkXOn1EmN1qk/HfnUcbVRZyYmZ4qpPea6sjB/pTJ0euyQp0Mk8ck+5T"
        crossorigin="anonymous"></script>
<script src="https://cdn.ckeditor.com/4.9.2/standard/ckeditor.js"></script>

<script>
    // Get the current year for the copyright
    $('#year').text(new Date().getFullYear());

    CKEDITOR.replace('description');
</script>
</body>

</html>

autodidact/app/templates/index.html
{% extends 'base.html' %}

{% block head_content %}
    <style>
        .table {
            margin-bottom: 0px;
        }

        .text {
            display: block;
            width: 200px;
            overflow: hidden;
            white-space: nowrap;
            text-overflow: ellipsis;
        }
    </style>
{% endblock %}

{% block body_content %}
    <!-- HEADER -->
    <header id="main-header" class="py-2 bg-primary text-white">
        <div class="container">
            <div class="row">
                <div class="col-md-6">
                    <h1>
                        <i class="fas fa-magic"></i>&nbsp; Trending</h1>
                </div>
            </div>
        </div>
    </header>
    <!-- ACTIONS -->
    <section id="actions" class="py-4 mb-4 bg-light">
        <div class="container">
            <div class="row">
                {% if user.is_authenticated %}
                    <div class="col-md-3">
                        <a href="{% url 'app:addPost' %}" class="btn btn-primary btn-block">
                            <i class="fas fa-plus"></i> Ask Question
                        </a>
                    </div>
                    <div class="col-md-3">
                        <a href="#" class="btn btn-success btn-block" data-toggle="modal"
                           data-target="#addCategoryModal">
                            <i class="fas fa-plus"></i> Add Tag
                        </a>
                    </div>
                {% else %}
                    <div class="col">
                        <p style="margin-bottom: 0px;">Please Sign In to contribute.</p>
                    </div>
                {% endif %}

            </div>
        </div>
    </section>

    <!-- POSTS -->
    <section id="posts">
        <div class="container">
            <div class="row">
                <div class="col-md-9">
                    <div class="card">
                        <div class="card-header">
                            <h4>Latest Posts</h4>
                        </div>
                        <table class="table table-striped">
                            {# TODO #}
                            <thead class="thead-dark text-center">
                            <tr style="text-align:left">
                                <th>#</th>
                                <th>Title</th>
                                <th>Views</th>
                                <th>Creation Time</th>
                                <th>Details</th>
                            </tr>
                            </thead>
                            <tbody>
                            {% for post in posts %}
                                <tr>
                                    <td>{{ forloop.counter }}</td>
                                    <td class="text">{{ post.title }}</td>
                                    <td>{{ post.viewers.all|length }}</td>
                                    <td>{{ post.creation_time }}</td>
                                    <td>
                                        <a href="{% url 'app:postDetails' post.id %}"
                                           class="btn btn-secondary">
                                            <i class="fas fa-angle-double-right"></i> Details
                                        </a>
                                    </td>
                                </tr>
                            {% empty %}
                                <tr>
                                    <td colspan="5">No Posts.</td>
                                </tr>
                            {% endfor %}
                            </tbody>
                        </table>
                    </div>
                    <br>
                    <div class="card" style="margin-top: 16px;">
                        <div class="card-header">
                            <h4>Latest Tags</h4>
                        </div>
                        <table class="table table-striped">
                            {# TODO #}
                            <thead class="thead-dark">
                            <tr style="text-align:left">
                                <th>#</th>
                                <th>Title</th>
                                <th>Date</th>
                                <th>Use Count</th>
                                <th>Details</th>
                            </tr>
                            </thead>
                            <tbody>
                            {% for tag in tags %}
                                <tr>
                                    <td>{{ forloop.counter }}</td>
                                    <td class="text">{{ tag.name }}</td>
                                    <td>{{ tag.creation_time }}</td>
                                    <td>{{ tag.use_count }}</td>
                                    <td>
                                        <a href="{% url 'app:tagDetails' tag.id %}" class="btn btn-secondary">
                                            <i class="fas fa-angle-double-right"></i> Details
                                        </a>
                                    </td>
                                </tr>
                            {% empty %}
                                <tr>
                                    <td colspan="5">No Tags.</td>
                                </tr>
                            {% endfor %}
                            </tbody>
                        </table>
                    </div>
                </div>
                <div class="col-md-3">
                    <div class="card text-center bg-primary text-white mb-3">
                        <div class="card-body">
                            <h3>Posts</h3>
                            <h4 class="display-4">
                                <i class="fas fa-clipboard"></i></i>
                                {{ n_posts }}
                            </h4>
                            <a href="{% url 'app:posts' %}" class="btn btn-outline-light btn-sm">View</a>
                            {#  TODO  #}
                        </div>
                    </div>

                    <div class="card text-center bg-success text-white mb-3">
                        <div class="card-body">
                            <h3>Tags</h3>
                            <h4 class="display-4">
                                <i class="fas fa-tags"></i>
                                {{ n_tags }}
                            </h4>
                            <a href="{% url 'app:tags' %}" class="btn btn-outline-light btn-sm">View</a>
                            {#  TODO  #}
                        </div>
                    </div>

                    <div class="card text-center bg-warning text-white mb-3">
                        <div class="card-body">
                            <h3>Users</h3>
                            <h4 class="display-4">
                                <i class="fas fa-users"></i>
                                {{ n_users }}
                            </h4>
                            <a href="{% url 'app:users' %}" class="btn btn-outline-light btn-sm">View</a>
                            {#  TODO  #}
                        </div>
                    </div>
                </div>
            </div>
    </section>
{% endblock %}

{% block below_footer_content %}
    <!-- MODALS -->

    <!-- ADD CATEGORY MODAL -->
    <div class="modal fade" id="addCategoryModal">
        <div class="modal-dialog modal-lg">
            <div class="modal-content">
                <div class="modal-header bg-success text-white">
                    <h5 class="modal-title">Add Tag</h5>
                    <button class="close" data-dismiss="modal">
                        <span>&times;</span>
                    </button>
                </div>
                <div class="modal-body">
                    <form action="{% url 'app:addTag' %}" method="post">
                        {% csrf_token %}
                        <div class="form-group">
                            <label for="title">Name of Tag</label>
                            <input type="text" class="form-control" name="tag">
                        </div>

                        <input type="submit" class="btn btn-success" value="Save">
                    </form>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

{% block below_body_content %}
{% endblock %}

autodidact/app/templates/pagination.html
<nav class="ml-4">
    <ul class="pagination">

        <li class="page-item {% if not items.has_previous %}disabled{% endif %}">
            <a href="{% if query %}?query={{ query }}&{% else %}?{% endif %}page=1" class="page-link">First</a>
        </li>

        <li class="page-item {% if not items.has_previous %}disabled{% endif %}">
            <a href="{% if query %}?query={{ query }}&{% else %}?{% endif %}page={% if items.has_previous %}{{ items.previous_page_number }}{% endif %}" class="page-link">Previous</a>
        </li>

        <li class="page-item active">
            <a href="#" class="page-link">{{ items.number }}</a>
        </li>

        <li class="page-item {% if not items.has_next %}disabled{% endif %}">
            <a href="{% if query %}?query={{ query }}&{% else %}?{% endif %}page={% if items.has_next %}{{ items.next_page_number }}{% endif %}" class="page-link">Next</a>
        </li>

        <li class="page-item {% if not items.has_next %}disabled{% endif %}">
            <a href="{% if query %}?query={{ query }}&{% else %}?{% endif %}page={{ items.paginator.num_pages }}" class="page-link">Last</a>
        </li>

    </ul>
</nav>